[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

board_build.filesystem = spiffs

lib_deps =
  me-no-dev/ESPAsyncWebServer @ ^1.2.3
  me-no-dev/AsyncTCP @ ^1.1.1
  adafruit/DHT sensor library
  adafruit/Adafruit Unified Sensor
  adafruit/Adafruit IO Arduino
  marcoschwartz/LiquidCrystal_I2C
  thinger.io/ThingerArduino
  bblanchon/ArduinoJson